config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.onelab.info/gmsh/gmsh:
      branch: master
      repo: https://gitlab.onelab.info/gmsh/gmsh
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.onelab.info/gmsh/gmsh git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ochre-gar.sh
        container: qc.acc_gloppy-pear-wasp
  QC.Doc:
    repos:
      gitlab.onelab.info/gmsh/gmsh find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ecru-mist.sh
        container: qc.doc_flimsy-maroon-snake
      gitlab.onelab.info/gmsh/gmsh git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-rust-opossum.sh
        container: qc.doc_thirsty-cyan-weasel
      gitlab.onelab.info/gmsh/gmsh markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-persimmon-coral.sh
        container: qc.doc_sunny-bistre-mammoth
      gitlab.onelab.info/gmsh/gmsh restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-bistre-emu.sh
        container: qc.doc_cheeky-mustard-warthog
  QC.Lic:
    repos:
      gitlab.onelab.info/gmsh/gmsh licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-magnolia-oyster.sh
        container: qc.lic_whiny-buff-kingfisher
  QC.Sec:
    repos:
      gitlab.onelab.info/gmsh/gmsh bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-goldenrod-manatee.sh
        container: qc.sec_paltry-white-lionfish
  QC.Sty:
    repos:
      gitlab.onelab.info/gmsh/gmsh checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-mustard-bombay.sh
        container: qc.sty_silly-beige-bullfrog
      gitlab.onelab.info/gmsh/gmsh flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-chocolate-sparrow.sh
        container: qc.sty_grumpy-sapphire-fowl
      gitlab.onelab.info/gmsh/gmsh jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-seashell-goat.sh
        container: qc.sty_cranky-turquoise-crab
      gitlab.onelab.info/gmsh/gmsh oclint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-copper-lemming.sh
        container: qc.sty_stuffy-burgundy-magpie
  QC.Uni:
    repos:
      gitlab.onelab.info/gmsh/gmsh pytest:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-taupe-magpie.sh
        container: qc.uni_baggy-green-lobster
  QC.Ver:
    repos:
      gitlab.onelab.info/gmsh/gmsh get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-goldenrod-penguin.sh
        container: qc.ver_skinny-cobalt-lion
timeout: 5400
