config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.onelab.info/gmsh/gmsh:
      branch: master
      repo: https://gitlab.onelab.info/gmsh/gmsh
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.onelab.info/gmsh/gmsh git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-periwinkle-oyster.sh
        container: qc.acc_gimpy-jade-avocet
  QC.Doc:
    repos:
      gitlab.onelab.info/gmsh/gmsh find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-goldenrod-bulldog.sh
        container: qc.doc_pokey-zucchini-ferret
      gitlab.onelab.info/gmsh/gmsh git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-maroon-tortoise.sh
        container: qc.doc_jumpy-cornflower-penguin
      gitlab.onelab.info/gmsh/gmsh markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-denim-tarsier.sh
        container: qc.doc_crappy-thistle-shrew
      gitlab.onelab.info/gmsh/gmsh restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-xanthic-wrasse.sh
        container: qc.doc_scummy-olive-bulldog
  QC.Lic:
    repos:
      gitlab.onelab.info/gmsh/gmsh licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-scarlet-ferret.sh
        container: qc.lic_snoopy-champagne-skunk
  QC.Sec:
    repos:
      gitlab.onelab.info/gmsh/gmsh bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-azure-panda.sh
        container: qc.sec_whiny-xanthic-angora
  QC.Sty:
    repos:
      gitlab.onelab.info/gmsh/gmsh checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-grey-magpie.sh
        container: qc.sty_randy-amaranth-millipede
      gitlab.onelab.info/gmsh/gmsh flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-periwinkle-bandicoot.sh
        container: qc.sty_pasty-periwinkle-neanderthal
      gitlab.onelab.info/gmsh/gmsh jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-burgundy-spider.sh
        container: qc.sty_crabby-seashell-slug
      gitlab.onelab.info/gmsh/gmsh oclint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-firebrick-caracal.sh
        container: qc.sty_fuzzy-violet-quoll
  QC.Uni:
    repos:
      gitlab.onelab.info/gmsh/gmsh pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-orchid-elephant.sh
        container: qc.uni_seedy-turquoise-booby
  QC.Ver:
    repos:
      gitlab.onelab.info/gmsh/gmsh get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-rose-boar.sh
        container: qc.ver_homey-plum-dachsbracke
timeout: 5400
