config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.onelab.info/gmsh/gmsh:
      branch: master
      repo: https://gitlab.onelab.info/gmsh/gmsh
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.onelab.info/gmsh/gmsh git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-brass-dingo.sh
        container: qc.acc_flimsy-amaranth-bonobo
  QC.Doc:
    repos:
      gitlab.onelab.info/gmsh/gmsh find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-periwinkle-molly.sh
        container: qc.doc_woozy-alizarin-coyote
      gitlab.onelab.info/gmsh/gmsh git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-copper-caterpillar.sh
        container: qc.doc_sleazy-apricot-dachsbracke
      gitlab.onelab.info/gmsh/gmsh markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-brown-zebu.sh
        container: qc.doc_shaggy-heliotrope-birman
      gitlab.onelab.info/gmsh/gmsh restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-harlequin-tetra.sh
        container: qc.doc_stinky-cyan-bongo
  QC.Lic:
    repos:
      gitlab.onelab.info/gmsh/gmsh licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-amethyst-pinscher.sh
        container: qc.lic_woozy-saffron-uakari
  QC.Sec:
    repos:
      gitlab.onelab.info/gmsh/gmsh bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lime-ostrich.sh
        container: qc.sec_pasty-flax-argentino
  QC.Sty:
    repos:
      gitlab.onelab.info/gmsh/gmsh checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-charcoal-pig.sh
        container: qc.sty_craggy-pink-mist
      gitlab.onelab.info/gmsh/gmsh flake8:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-chartreuse-rat.sh
        container: qc.sty_greasy-viridian-moose
      gitlab.onelab.info/gmsh/gmsh jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-violet-eleuth.sh
        container: qc.sty_zippy-cobalt-fossa
      gitlab.onelab.info/gmsh/gmsh oclint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-burgundy-hare.sh
        container: qc.sty_stinky-aqua-spaniel
  QC.Uni:
    repos:
      gitlab.onelab.info/gmsh/gmsh pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-lemon-quail.sh
        container: qc.uni_skimpy-azure-sheepdog
  QC.Ver:
    repos:
      gitlab.onelab.info/gmsh/gmsh get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-gamboge-fly.sh
        container: qc.ver_homely-firebrick-maltese
timeout: 5400
